name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'
      
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version=8.5
      
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      
      - name: Run tests
        run: ./gradlew test
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdu-seat-jar
          path: build/libs/*.jar
          retention-days: 30
